#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 26 22:41:00 2022

@author: chrishunter
"""
OVOID_1 = {}
OVOID_1[length] = 150
top_height = 100 
bottom_height = 50
top_scale = 50
bottom_scale = 50
side_scale = 75
color='black'
fill=color
width=10
